language: node_js
node_js:
  "node"

before_script:
  - npm ci

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build

stages:
  - lint
  - build

notifications:
  email: false
