language: node_js
node_js:
  "node"

before_script:
  - npm ci

jobs:
  include:
    - stage: test
      script: npm run test:unit
    - stage: build
      script: npm run build

stages:
  - test
  - build

notifications:
  email: false
